/**
 * Created by peter on 7/10/17.
 */

interface mountcallbacks{
    readdir:(path:string,cb)=> void
    open:(path:string,cb)=>void
    statfs:(options,cb) => void

}
export function mount(mountpath:string,mountoptions:mountcallbacks, callback:(error)=> void):void
export function unmount();

export const EPERM: number;
export const ENOENT: number;
export const ESRCH: number;
export const EINTR: number;
export const EIO: number;
export const ENXIO: number;
export const E2BIG: number;
export const ENOEXEC: number;
export const EBADF: number;
export const ECHILD: number;
export const EAGAIN: number;
export const ENOMEM: number;
export const EACCES: number;
export const EFAULT: number;
export const ENOTBLK: number;
export const EBUSY: number;
export const EEXIST: number;
export const EXDEV: number;
export const ENODEV: number;
export const ENOTDIR: number;
export const EISDIR: number;
export const EINVAL: number;
export const ENFILE: number;
export const EMFILE: number;
export const ENOTTY: number;
export const ETXTBSY: number;
export const EFBIG: number;
export const ENOSPC: number;
export const ESPIPE: number;
export const EROFS: number;
export const EMLINK: number;
export const EPIPE: number;
export const EDOM: number;
export const ERANGE: number;
export const EDEADLK: number;
export const ENAMETOOLONG: number;
export const ENOLCK: number;
export const ENOSYS: number;
export const ENOTEMPTY: number;
export const ELOOP: number;
export const EWOULDBLOCK: number;
export const ENOMSG: number;
export const EIDRM: number;
export const ECHRNG: number;
export const EL2NSYNC: number;
export const EL3HLT: number;
export const EL3RST: number;
export const ELNRNG: number;
export const EUNATCH: number;
export const ENOCSI: number;
export const EL2HLT: number;
export const EBADE: number;
export const EBADR: number;
export const EXFULL: number;
export const ENOANO: number;
export const EBADRQC: number;
export const EBADSLT: number;
export const EDEADLOCK: number;
export const EBFONT: number;
export const ENOSTR: number;
export const ENODATA: number;
export const ETIME: number;
export const ENOSR: number;
export const ENONET: number;
export const ENOPKG: number;
export const EREMOTE: number;
export const ENOLINK: number;
export const EADV: number;
export const ESRMNT: number;
export const ECOMM: number;
export const EPROTO: number;
export const EMULTIHOP: number;
export const EDOTDOT: number;
export const EBADMSG: number;
export const EOVERFLOW: number;
export const ENOTUNIQ: number;
export const EBADFD: number;
export const EREMCHG: number;
export const ELIBACC: number;
export const ELIBBAD: number;
export const ELIBSCN: number;
export const ELIBMAX: number;
export const ELIBEXEC: number;
export const EILSEQ: number;
export const ERESTART: number;
export const ESTRPIPE: number;
export const EUSERS: number;
export const ENOTSOCK: number;
export const EDESTADDRREQ: number;
export const EMSGSIZE: number;
export const EPROTOTYPE: number;
export const ENOPROTOOPT: number;
export const EPROTONOSUPPORT: number;
export const ESOCKTNOSUPPORT: number;
export const EOPNOTSUPP: number;
export const EPFNOSUPPORT: number;
export const EAFNOSUPPORT: number;
export const EADDRINUSE: number;
export const EADDRNOTAVAIL: number;
export const ENETDOWN: number;
export const ENETUNREACH: number;
export const ENETRESET: number;
export const ECONNABORTED: number;
export const ECONNRESET: number;
export const ENOBUFS: number;
export const EISCONN: number;
export const ENOTCONN: number;
export const ESHUTDOWN: number;
export const ETOOMANYREFS: number;
export const ETIMEDOUT: number;
export const ECONNREFUSED: number;
export const EHOSTDOWN: number;
export const EHOSTUNREACH: number;
export const EALREADY: number;
export const EINPROGRESS: number;
export const ESTALE: number;
export const EUCLEAN: number;
export const ENOTNAM: number;
export const ENAVAIL: number;
export const EISNAM: number;
export const EREMOTEIO: number;
export const EDQUOT: number;
export const ENOMEDIUM: number;
export const EMEDIUMTYPE: number;